### ISSUE TITLE
import torch is missing from modules\utils.py

### ISSUE THREAD

**Issue by dchatel** [ltdrdata/ComfyUI-Impact-Subpack#11]
# ComfyUI Error Report
## Error Details
- **Node ID:** 1880:3
- **Node Type:** SegmDetectorCombined_v2
- **Exception Type:** NameError
- **Exception Message:** name 'torch' is not defined
## Stack Trace
```
  File "G:\ai\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\ai\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\ai\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "G:\ai\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 163, in doit
    mask = segm_detector.detect_combined(image, threshold, dilation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack\modules\subcore.py", line 269, in detect_combined
    return utils.combine_masks(segmasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack\modules\utils.py", line 92, in combine_masks
    mask = torch.from_numpy(combined_cv2_mask)
           ^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.7-14-g7a7efe8
- **Arguments:** main.py --output-directory G:\ai\outputs --use-pytorch-cross-attention --front-end-version Comfy-Org/ComfyUI_frontend@latest
- **OS:** nt
- **Python Version:** 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 20188176442
  - **Torch VRAM Total:** 3858759680
  - **Torch VRAM Free:** 28254266

## Logs
```
2024-12-11T20:12:50.307378 - [START] Security scan2024-12-11T20:12:50.307378 - 
2024-12-11T20:12:51.384215 - [DONE] Security scan2024-12-11T20:12:51.384215 - 
2024-12-11T20:12:51.488488 - ## ComfyUI-Manager: installing dependencies done.2024-12-11T20:12:51.488488 - 
2024-12-11T20:12:51.488488 - ** ComfyUI startup time:2024-12-11T20:12:51.488488 -  2024-12-11T20:12:51.489488 - 2024-12-11 20:12:51.4884882024-12-11T20:12:51.489488 - 
2024-12-11T20:12:51.502592 - ** Platform:2024-12-11T20:12:51.502592 -  2024-12-11T20:12:51.502592 - Windows2024-12-11T20:12:51.502592 - 
2024-12-11T20:12:51.502592 - ** Python version:2024-12-11T20:12:51.502592 -  2024-12-11T20:12:51.502592 - 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]2024-12-11T20:12:51.502592 - 
2024-12-11T20:12:51.502592 - ** Python executable:2024-12-11T20:12:51.502592 -  2024-12-11T20:12:51.502592 - C:\Users\dchat\miniconda3\envs\comfy\python.exe2024-12-11T20:12:51.502592 - 
2024-12-11T20:12:51.503593 - ** ComfyUI Path:2024-12-11T20:12:51.503593 -  2024-12-11T20:12:51.503593 - G:\ai\ComfyUI2024-12-11T20:12:51.503593 - 
2024-12-11T20:12:51.503593 - ** Log path:2024-12-11T20:12:51.503593 -  2024-12-11T20:12:51.503593 - G:\ai\ComfyUI\comfyui.log2024-12-11T20:12:51.503593 - 
2024-12-11T20:12:53.121930 - 
Prestartup times for custom nodes:2024-12-11T20:12:53.121930 - 
2024-12-11T20:12:53.121930 -    0.0 seconds:2024-12-11T20:12:53.121930 -  2024-12-11T20:12:53.122930 - G:\ai\ComfyUI\custom_nodes\rgthree-comfy2024-12-11T20:12:53.122930 - 
2024-12-11T20:12:53.122930 -    2.8 seconds:2024-12-11T20:12:53.122930 -  2024-12-11T20:12:53.122930 - G:\ai\ComfyUI\custom_nodes\ComfyUI-Manager2024-12-11T20:12:53.122930 - 
2024-12-11T20:12:53.122930 - 
2024-12-11T20:12:54.531359 - Total VRAM 24564 MB, total RAM 32581 MB
2024-12-11T20:12:54.531359 - pytorch version: 2.4.1+cu124
2024-12-11T20:12:54.532359 - Set vram state to: NORMAL_VRAM
2024-12-11T20:12:54.532359 - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-12-11T20:12:55.403592 - Using pytorch cross attention
2024-12-11T20:12:56.533571 - Initializing frontend: Comfy-Org/ComfyUI_frontend@latest, requesting version details from GitHub...
2024-12-11T20:12:56.805926 - [Prompt Server] web root: G:\ai\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.5.12
2024-12-11T20:12:56.807926 - Adding extra search path checkpoints g:/ai/models/checkpoints/
2024-12-11T20:12:56.807926 - Adding extra search path controlnet g:/ai/models/controlnet/
2024-12-11T20:12:56.807926 - Adding extra search path embeddings g:/ai/models/embeddings/
2024-12-11T20:12:56.807926 - Adding extra search path loras g:/ai/models/loras/
2024-12-11T20:12:56.808926 - Adding extra search path upscale_models g:/ai/models/upscale_models/
2024-12-11T20:12:56.808926 - Adding extra search path vae g:/ai/models/vae/
2024-12-11T20:12:57.218090 - C:\Users\dchat\miniconda3\envs\comfy\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
2024-12-11T20:12:58.774035 - [Crystools [0;32mINFO[0m] Crystools version: 1.21.0
2024-12-11T20:12:58.788289 - [Crystools [0;32mINFO[0m] CPU: 12th Gen Intel(R) Core(TM) i7-12700KF - Arch: AMD64 - OS: Windows 10
2024-12-11T20:12:58.796405 - [Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
2024-12-11T20:12:58.796405 - [Crystools [0;32mINFO[0m] GPU/s:
2024-12-11T20:12:58.815497 - [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4090
2024-12-11T20:12:58.815497 - [Crystools [0;32mINFO[0m] NVIDIA Driver: 566.36
2024-12-11T20:12:58.863037 - ### Loading: ComfyUI-Impact-Pack (V8.0.1)2024-12-11T20:12:58.863037 - 
2024-12-11T20:12:58.920696 - [Impact Pack] Wildcards loading done.2024-12-11T20:12:58.920696 - 
2024-12-11T20:12:58.922695 - ### Loading: ComfyUI-Impact-Subpack (V1.0)2024-12-11T20:12:58.922695 - 
2024-12-11T20:12:58.924696 - ### Loading: ComfyUI-Inspire-Pack (V1.9)2024-12-11T20:12:58.924696 - 
2024-12-11T20:12:58.972159 - Total VRAM 24564 MB, total RAM 32581 MB
2024-12-11T20:12:58.972159 - pytorch version: 2.4.1+cu124
2024-12-11T20:12:58.973160 - Set vram state to: NORMAL_VRAM
2024-12-11T20:12:58.973160 - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-12-11T20:12:59.006602 - ### Loading: ComfyUI-Manager (V2.55.4)2024-12-11T20:12:59.006602 - 
2024-12-11T20:12:59.152229 - ### ComfyUI Version: v0.3.7-14-g7a7efe8 | Released on '2024-12-11'2024-12-11T20:12:59.152229 - 
2024-12-11T20:12:59.476901 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: G:\ai\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
2024-12-11T20:12:59.476901 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-11T20:12:59.476901 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-11T20:12:59.496133 - DWPose: Onnxruntime with acceleration providers detected2024-12-11T20:12:59.496133 - 
2024-12-11T20:12:59.605892 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-11T20:12:59.605892 - 
2024-12-11T20:12:59.661340 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-11T20:12:59.662341 - 
2024-12-11T20:12:59.667426 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-11T20:12:59.667426 - 
2024-12-11T20:12:59.689601 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-11T20:12:59.689601 - 
2024-12-11T20:12:59.776631 - [34mFizzleDorf Custom Nodes: [92mLoaded[0m2024-12-11T20:12:59.776631 - 
2024-12-11T20:12:59.811922 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-11T20:12:59.811922 - 
2024-12-11T20:12:59.855396 - 
2024-12-11T20:12:59.855396 - [92m[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉[00m2024-12-11T20:12:59.855396 - 
2024-12-11T20:12:59.855396 - 
2024-12-11T20:12:59.858396 - 
Import times for custom nodes:
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\srl-nodes
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\Uncond-Zero-for-ComfyUI
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\SD-Latent-Interposer
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\comfyui_lora_tag_loader
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\Skimmed_CFG
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
2024-12-11T20:12:59.859396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\cg-use-everywhere
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-MakeFrame
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Image-Inpainting
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-ELLA
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI_essentials
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\comfyui_davcha
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\rgthree-comfy
2024-12-11T20:12:59.860397 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-LTXVideo
2024-12-11T20:12:59.861396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-12-11T20:12:59.861396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-12-11T20:12:59.861396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-12-11T20:12:59.861396 -    0.0 seconds: G:\ai\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-11T20:12:59.861396 -    0.1 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI_Searge_LLM
2024-12-11T20:12:59.861396 -    0.1 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-12-11T20:12:59.861396 -    0.1 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-12-11T20:12:59.861396 -    0.2 seconds: G:\ai\ComfyUI\custom_nodes\comfyui_facetools
2024-12-11T20:12:59.861396 -    0.3 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-12-11T20:12:59.861396 -    0.3 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-12-11T20:12:59.861396 -    0.3 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-11T20:12:59.861396 -    0.6 seconds: G:\ai\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-12-11T20:12:59.861396 - 
2024-12-11T20:12:59.870476 - Setting output directory to: G:\ai\outputs
2024-12-11T20:12:59.871476 - Starting server

2024-12-11T20:12:59.871476 - To see the GUI go to: http://127.0.0.1:8188
2024-12-11T20:13:02.289588 - FETCH DATA from: G:\ai\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-11T20:13:02.289588 - 2024-12-11T20:13:02.293588 -  [DONE]2024-12-11T20:13:02.293588 - 
2024-12-11T20:14:13.492655 - got prompt
2024-12-11T20:14:13.922564 - model weight dtype torch.float16, manual cast: None
2024-12-11T20:14:13.923564 - model_type EPS
2024-12-11T20:14:15.869592 - Using pytorch attention in VAE
2024-12-11T20:14:15.871592 - Using pytorch attention in VAE
2024-12-11T20:14:16.311729 - loaded straight to GPU
2024-12-11T20:14:16.312729 - Requested to load BaseModel
2024-12-11T20:14:16.321727 - loaded completely 9.5367431640625e+25 1639.406135559082 True
2024-12-11T20:14:16.434808 - Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
2024-12-11T20:14:16.911689 - using sdpa for attention2024-12-11T20:14:16.911689 - 
2024-12-11T20:14:17.303056 - No flash_attn import to remove2024-12-11T20:14:17.303056 - 
2024-12-11T20:14:22.222471 - None 0-1: 
bland dull monochrome sepia blurry blurry_vision
(worst quality, low quality, normal quality:1.2)
embedding:badhandv4_2
embedding:srn_48
embedding:srn_49
embedding:srn_51
2024-12-11T20:14:22.223471 - 
2024-12-11T20:14:22.228471 - Requested to load SD1ClipModel
2024-12-11T20:14:22.353806 - loaded completely 9.5367431640625e+25 235.84423828125 True
2024-12-11T20:14:22.525390 - G:\ai\ComfyUI\comfy\ldm\modules\attention.py:418: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
2024-12-11T20:14:22.573562 - detected lora tag: ('lora', 'skin_tone_slider_v1.safetensors', -1.0, -1.0) >> skin_tone_slider_v1.safetensors2024-12-11T20:14:22.573562 - 
2024-12-11T20:14:22.619563 - Requested to load SD1ClipModel
2024-12-11T20:14:22.781989 - loaded completely 9.5367431640625e+25 235.84423828125 True
2024-12-11T20:14:22.798990 - end_frame at 0, using max_frames instead!2024-12-11T20:14:22.798990 - 
2024-12-11T20:14:23.941441 - 
2024-12-11T20:14:24.199844 - 0: 640x384 1 speech-bubble, 41.0ms
2024-12-11T20:14:24.200844 - Speed: 2.0ms preprocess, 41.0ms inference, 30.1ms postprocess per image at shape (1, 3, 640, 384)
2024-12-11T20:14:24.203844 - !!! Exception during processing !!! name 'torch' is not defined
2024-12-11T20:14:24.212844 - Traceback (most recent call last):
  File "G:\ai\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ai\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 163, in doit
    mask = segm_detector.detect_combined(image, threshold, dilation)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack\modules\subcore.py", line 269, in detect_combined
    return utils.combine_masks(segmasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack\modules\utils.py", line 92, in combine_masks
    mask = torch.from_numpy(combined_cv2_mask)
           ^^^^^
NameError: name 'torch' is not defined

2024-12-11T20:14:24.213844 - Prompt executed in 10.70 seconds

```

**Comment by ltdrdata** [comment]
Fixed. Please update to latest version
